/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hearthstone.forecast;

import static com.sun.webkit.graphics.WCImage.getImage;
import java.awt.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Image;
import static java.awt.Image.SCALE_DEFAULT;
import java.awt.image.*;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bates_844187
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    int height = 0;
    Image car;

    public GUI(boolean no)
    {
        boolean yes = no;
    }

    public GUI() throws IOException {
        initComponents();
        
        BufferedImage image = null;
        height = Main.getHeight();
        Mana0.setBackground(Color.black);
        int manaCost;
        
        JPanel[] manaP = new JPanel[8];
        
        JLabel[][] cards = new JLabel[8][10];
        
        cards[0][0] = Card0_0;
        cards[0][1] = Card0_0;
        cards[0][2] = Card0_0;
        cards[0][3] = Card0_0;
        cards[0][4] = Card0_0;
        
        manaP[0] = Mana0;
        
        for(JPanel p : manaP){
            p = new JPanel();
            p.setPreferredSize(new Dimension(1080, (int) (14 * (height / 100))));
        }
        
        
        manaCost = 0;
        for(JPanel p : manaP){
            Main.add(p);
            
            for(JLabel l : cards[manaCost]){
               p.add(Card0_0);
            }
            manaCost++;
        }
        
        
        ResizeSet("http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_066.png", Card0_0, (int) (1 * 15 * (height / 100)), (int) (.66 * (1 * 15 * (height / 100))));
        
        System.out.println(height);
        //Mana0.setPreferredSize(new Dimension(500, 500));
        Mana0.setPreferredSize(new Dimension(1080, (int) (14 * (height / 100))));
    }
    
    public void ResizeSet(String link, JLabel label, int h, int w) throws MalformedURLException, IOException{
        URL url = new URL(link);
        BufferedImage image = ImageIO.read(url);
        ImageIcon icon = new ImageIcon(image);
        label.setIcon(icon);
        BufferedImage resizedImage = resize (image,w,h);
        resizedImage = resizedImage.getSubimage((int)(w * .05), (int)(h * .1), (int)(w * .9), (int)(h *.85));
        icon.setImage(resizedImage);
    }
    
//Component from the internet
    public static BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Mana0 = new javax.swing.JPanel();
        Card0_0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setPreferredSize(new java.awt.Dimension(1080, 1080));

        Mana0.setBackground(new java.awt.Color(200, 13, 4));
        Mana0.setForeground(new java.awt.Color(5, 76, 4));

        Card0_0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Card0_0.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout Mana0Layout = new javax.swing.GroupLayout(Mana0);
        Mana0.setLayout(Mana0Layout);
        Mana0Layout.setHorizontalGroup(
            Mana0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mana0Layout.createSequentialGroup()
                .addComponent(Card0_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        Mana0Layout.setVerticalGroup(
            Mana0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mana0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Card0_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mana0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mana0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(769, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try{
                    GUI a = new GUI();
                    new GUI().setVisible(true);
                }
                catch(IOException e){System.out.println(e);}
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card0_0;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Mana0;
    // End of variables declaration//GEN-END:variables
}
